### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by cbenhagen** [hcbpassos/drag_select_grid_view#19]
It would be awesome if this package could be [migrated to null safety](https://dart.dev/null-safety/migration-guide).

**Comment by cbenhagen** [comment]
I added a PR: #20.

Anyone who wants to use it today can add the following to their `pubspec.yaml`:
```yaml
dependency_overrides:
  drag_select_grid_view:
    git:
      url: git@github.com:cbenhagen/drag_select_grid_view
      ref: null-safety
```
